name: lowresrmx
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  re_editor:
    path: ../re_editor
  sw_rend: ^0.0.2
  provider: ^6.1.2
  ffi: ^2.1.2
  path: ^1.9.0
  path_provider: ^2.1.3
  package_info_plus: ^9.0.0
  shared_preferences: ^2.2.3
  mp_audio_stream: ^0.2.2
  image: ^4.2.0
  markdown_widget: ^2.3.2+6
  re_highlight: ^0.0.3
  # stream_mixin: ^3.0.4
  # googleapis: ^13.1.0
  # googleapis_auth: ^1.6.0
  # extension_google_sign_in_as_googleapis_auth: ^2.0.12
  # google_sign_in: ^6.2.1
  # http: ^1.2.1
  # flutter_secure_storage: ^9.2.2
  core_plugin:
    path: ../core_plugin
  # cloud_firestore: ^5.0.1
  slider_listtile: ^1.0.0
  share_handler: ^0.0.21
  # keyboard_attachable: ^2.2.0
  flutter_keyboard_visibility: ^6.0.0
  share_plus: ^12.0.1
  file_picker: ^10.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  change_app_package_name: ^1.2.0

flutter:
  uses-material-design: true
  assets:
    - asset/manual.md

  fonts:
    - family: RecursiveLinear
      fonts:
        - asset: asset/RecMonoLinear-Regular-1.085.ttf
        - asset: asset/RecMonoLinear-Italic-1.085.ttf
          style: italic
        - asset: asset/RecMonoLinear-Bold-1.085.ttf
          weight: 700
        - asset: asset/RecMonoLinear-BoldItalic-1.085.ttf
          weight: 700
          style: italic

